[tool.poetry]
name = "y"
version = "0.1.0"
description = "fizzbuzzTryPoetry"
authors = ["y"]

[tool.poetry.dependencies]
python = "*"

[tool.poetry.dev-dependencies]
pytest = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
